Adding mobile navbar css and javascript
pedrorosa-dev/web-pass-gen pull request #2
Opened 2023-12-19 21:09 UTC by zabeluna

## Description
- CSS, JavaScript and changes to the HTML were added to create a mobile menu.

## What was done?
- The responsive hamburger menu was created using CSS.
- The responsive menu was configured with JavaScript to allow user interaction.

## Notes
- A new div for the logo was implemented to improve responsiveness and allow for switching between desktop and mobile.

2023-12-19 22:04 UTC, pedrorosa-dev reviewed
Comentarios finalizados

2023-12-19 22:04 UTC, pedrorosa-dev commented on assets/styles/desktop/navbar.css
> +    display: block;
Ficou perfeito o css 😆

2023-12-19 22:04 UTC, pedrorosa-dev commented on assets/styles/desktop/navbar.css
> +.nav-bar {
E os commits faltou os prefixos.

2023-12-19 22:05 UTC, zabeluna commented on assets/styles/mobile/mobile-nav-bar.js
> +const navButton = document.querySelector("#hamburger-toggle");
Obrigada!

2023-12-19 22:06 UTC, zabeluna commented on assets/styles/desktop/navbar.css
> +    display: block;
Muito obrigada!

2023-12-19 22:07 UTC, pedrorosa-dev requested changes
Pedido de Alteração: Mexer na nav bar

2023-12-19 22:11 UTC, pedrorosa-dev approved these changes

2023-12-19 22:12 UTC, pedrorosa-dev requested changes
"Change Request: Adjustments to the Navbar"

2023-12-20 01:08 UTC, pedrorosa-dev approved these changes

2023-12-20 01:08 UTC, merged